server:
  port: 8080
#redis
spring:
  redis:
    database: 0
    host: 192.168.56.102
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
      timeout: 3000